"""Sample resumes for the picker — generated by scripts/prepare_samples.py."""

import json
import os

from demo import config


def load_samples() -> list:
    if not os.path.exists(config.SAMPLES_JSON):
        return []
    with open(config.SAMPLES_JSON) as f:
        return json.load(f)
